### PR TITLE
added filtering reverse geocoding feature

### PR DESCRIPTION
**Pull request by 20tab**
Issue #7

### CODE REVIEW

**Comment by 20tab** [comment]
Travis CI checks failed on pre-existent code

**Comment by swistakm** [comment]
Thanks for contribution. I will take a look at the end if month because now I'm on vacation.

-----Wiadomość oryginalna-----
Od: 20tab srl
Wysłano: 2015-08-24 15:59
Do: swistakm/python-gmaps
Temat: Re: [python-gmaps] added filtering reverse geocoding feature (#8)

Travis CI checks failed on pre-existent code

**Comment by gabbork** [comment]
thank you

**Comment by swistakm** [comment]
Merged and released. Thank you very much!

**Comment by gabbork** [comment]
Cool. Last detail: maybe you should put an advise in the doc telling that some feature (as filtered reverse geocoding) needs the api KEY to work.
https://developers.google.com/maps/documentation/geocoding/intro#ReverseGeocoding
Thanks!

**Comment by swistakm** [comment]
note added

**Pull request merged**
